version : '3.8'
services:
  B-App:
   image: gbaderobusola/busola:my-app-1.1
   ports:
    - 8081:80
  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pwd
